# Creates A Version Witch Adapter Switch and Rationals
{
    name: Plain,
    #  magma settings
    from_checkpoint: False,
    # dtype: float16,
    perceiver: False,


    # image encoder settings
    encoder_name: 'clip_resnet_large',
    freeze_img_encoder: True,
    rational_image_encoder: False,

    # adapter settings
    adapter_config: {"mlp": {"adapter_type": "normal", "downsample_factor": 4}, "adapter_switch": False, "hidden_act": "relu" },


    # train settings
    batch_size: 32,
    train_steps: 150000,
    lr: 8.0e-4,
    min_lr: 0.0,
    lr_decay_iters: 300000,
    image_enc_lr: 2.0e-6,
    use_image_embed_layernorm: true,
    image_embed_dropout_prob: 0.1,
    image_size: 384,

    gradient_accumulation_steps: 4,
    zero_stage: 2,
    gradient_clipping: 1.0,

    # dataset / save / load settings
    train_dataset_name: 'scrambled_eggs',
    #train_dataset_dir: '/mnt/localdisk/conceptual_captions',
    train_dataset_dir: [
            '/pfss/alephalpha/datasets-tokenized/aa-data-multimodal-large-tokenized/laion/laion_index_dataset',
            '/pfss/alephalpha/datasets-tokenized/aa-data-multimodal-large-tokenized/CC3M_converted/CC3M_converted_index_dataset',
        #'/mnt/localdisk/localized_narratives',
        '/pfss/alephalpha/datasets-tokenized/aa-data-multimodal-large-tokenized/visual_genome_converted/visual_genome_converted_index_dataset',
        '/pfss/alephalpha/datasets-tokenized/aa-data-multimodal-large-tokenized/hateful_memes_converted/hateful_memes_converted_index_dataset',
        '/pfss/alephalpha/datasets-tokenized/aa-data-multimodal-large-tokenized/coco_converted/coco_converted_index_dataset',
        '/pfss/alephalpha/datasets-tokenized/aa-data-multimodal-large-tokenized/wit_converted/wit_converted_index_dataset',
        '/pfss/alephalpha/datasets-tokenized/aa-data-multimodal-large-tokenized/gqa_train_converted/gqa_train_converted_index_dataset',
        '/pfss/alephalpha/datasets-tokenized/aa-data-multimodal-large-tokenized/vqa_train_converted/vqa_train_converted_index_dataset',
        '/pfss/alephalpha/datasets-tokenized/aa-data-multimodal-large-tokenized/okvqa_train_converted/okvqa_train_converted_index_dataset'
        ],

    train_micro_batch_size_per_gpu: 2,
    #eval_dataset_name: 'coco',
    #eval_dataset_dir: '/mnt/localdisk/coco_data',
    eval_dataset_dir: Null,

    save: "/nfs/scratch_2/bjoern/checkpoints/magma_ablation/plain_magma_2/",
    #load: "/nfs/scratch_2/bjoern/checkpoints/magma_ablation/plain_magma/",
    #load: "/mnt/shared_vol/checkpoints/multimodal_transformer_rn50x16",
    wandb_project: "magma_ablations",

    eval_every: 250,
    save_every: 250,
}
